# Generated by Django 5.1 on 2024-11-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='pet',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pets/img'),
        ),
    ]
