# Generated by Django 5.1 on 2024-11-28 22:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_nome_pet_titulo_alter_pet_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='pet',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pet',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pets/img/'),
        ),
    ]
