# Generated by Django 5.1 on 2024-11-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
