# Generated by Django 5.1 on 2024-11-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='pet',
            name='cep',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('macho', 'Macho'), ('femea', 'Fêmea'), ('nao_informado', 'Não Informado')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
